const disciplinas = [
  {
    nome: 'ALGORITMOS E PROGRAMACAO DE COMPUTADORES',
    creditos: 6,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 1,
  },

  {
    nome: 'FORMACAO DOCENTE EM COMPUTACAO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 1,
  },

  {
    nome: 'ORGANIZACAO DA EDUCACAO BRASILEIRA',
    creditos: 4,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 1,
  },

  {
    nome: 'CALCULO 1',
    creditos: 6,
    provas: true,
    trabalhos: false,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 2,
  },

  {
    nome: 'FUNDAMENTOS TEORICOS DA COMPUTACAO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 2,
  },

  {
    nome: 'ESTRUTURA DE DADOS',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 2,
  },

  {
    nome: 'PSICOLOGIA DA EDUCACAO',
    creditos: 4,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 2,
  },

  {
    nome: 'INTRODUCAO A ALGEBRA LINEAR',
    creditos: 4,
    provas: true,
    trabalhos: false,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 3,
  },

  {
    nome: 'PROBABILIDADE E ESTATISTICA',
    creditos: 4,
    provas: true,
    trabalhos: false,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 3,
  },

  {
    nome: 'LOGICA COMPUTACIONAL 1',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 3,
  },

  {
    nome: 'TECNICAS DE PROGRAMACAO 1',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 3,
  },

  {
    nome: 'CALCULO 2',
    creditos: 6,
    provas: true,
    trabalhos: false,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 4,
  },

  {
    nome: 'ORGANIZACAO DE ARQUIVOS',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 4,
  },

  {
    nome: 'LINGUAGENS DE PROGRAMACAO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 4,
  },

  {
    nome: 'ARQUITETURA DE PROCESSADORES DIGITAIS',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 4,
  },

  {
    nome: 'METODOS DE PESQUISA NA LICENCIATURA EM COMPUTACAO',
    creditos: 2,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 4,
  },

  {
    nome: 'BANCO DE DADOS',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 5,
  },

  {
    nome: 'PRODUCAO DE MATERIAL DIDATICO',
    creditos: 5,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 5,
  },

  {
    nome: 'SUPERVISAO DE PRODUCAO DE MATERIAL DIDATICO',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 5,
  },

  {
    nome: 'INTRODUCAO A SISTEMAS OPERACIONAIS',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 5,
  },

  {
    nome: 'PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTACAO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 5,
  },

  {
    nome: 'DIDATICA FUNDAMENTAL',
    creditos: 4,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 5,
  },

  {
    nome: 'REDES DE COMPUTADORES',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 6,
  },

  {
    nome: 'PROJETO E ANALISE DE ALGORITMOS',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 6,
  },

  {
    nome: 'PRATICA PEDAGOGICA EM COMPUTACAO 1',
    creditos: 6,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 6,
  },

  {
    nome: 'SUPERVISAO DE PRATICA PEDAGOGICA EM COMPUTACAO 1',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 6,
  },

  {
    nome: 'SEGURANCA COMPUTACIONAL',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 7,
  },

  {
    nome: 'SISTEMAS DE INFORMACAO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 7,
  },

  {
    nome: 'ENGENHARIA DE SOFTWARE',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 7,
  },

  {
    nome: 'PRODUCAO CIENTIFICA NA LICENCIATURA EM COMPUTACAO',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 7,
  },

  {
    nome: 'SUPERVISAO DE PRATICA PEDAGOGICA EM COMPUTACAO 2',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 7,
  },

  {
    nome: 'PRATICA PEDAGOGICA EM COMPUTACAO 2',
    creditos: 6,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 7,
  },

  {
    nome: 'INFORMATICA APLICADA A EDUCACAO',
    creditos: 4,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'TEORIA DA COMPUTACAO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTACAO',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'ESTAGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTACAO 1',
    creditos: 7,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'SUPERVISAO DE ESTAGIO EM LICENCIATURA EM COMPUTACAO 1',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'LINGUA DE SINAIS BRASILEIRA - BASICO',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'ADMINISTRACAO DAS ORGANIZACOES EDUCATIVAs',
    creditos: 4,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 8,
  },

  {
    nome: 'ESTAGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTACAO 2',
    creditos: 7,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 9,
  },

  {
    nome: 'SUPERVISAO DE ESTAGIO EM LICENCIATURA EM COMPUTACAO 2',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 9,
  },

  {
    nome: 'ESTAGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTACAO 3',
    creditos: 7,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 9,
  },

  {
    nome: 'SUPERVISAO DE ESTAGIO EM LICENCIATURA EM COMPUTACAO 3',
    creditos: 2,
    provas: false,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 9,
  },

  {
    nome: 'TOPICOS AVANCADOS EM COMPUTADOREs',
    creditos: 4,
    provas: true,
    trabalhos: true,
    estudo: 0,
    nota: 0,
    desempenho: 0,
    reprovado: false,
    semestre: 9,
  },
];

export default disciplinas;
